apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
  keycloak_admin: YWRtaW4=
  keycloak_admin_password: YWRtaW4=