apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-wars-deployment
spec:
  selector:
    matchLabels:
      app: star-wars
  replicas: 2
  template:
    metadata:
      labels:
        app: star-wars
    spec:
      containers:
        - name: star-wars
          image: mouridamine/sw:1.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
       - name: config-volume
       configMap:
         name: app-config