apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: kc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-app
  template:
    metadata:
      labels:
        app: kc-app
    spec:
      containers:
        - name: kc-app
          image: quay.io/keycloak/keycloak:25.0.4
          ports:
            - containerPort: 80
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: keycloak_admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: keycloak_admin_password
---
apiVersion: v1
kind: Service
metadata:
  name: kc-app-service
spec:
  type: NodePort
  selector:
    app: kc-app
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 80
      nodePort: 30102
