apiVersion: v1
kind: Service
metadata:
  name: sw-service
spec:
  selector:
    app: star-wars
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
      nodePort: 31001
