apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
  namespace: tekton-app

spec:
  params:
    - name: dockerfile
      type: string
      default: ./Dockerfile
    - name: image
      type: string
  workspaces:
    - name: source
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      workspaces:
        - name: source
          workspace: source
      params:
        - name: dockerfile
          value: $(params.dockerfile)
        - name: image
          value: $(params.image)
