apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-deploy-run
  namespace: tekton-app
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: source
      resourceRef:
        name: git-source
  params:
    - name: dockerfile
      value: ./Dockerfile
    - name: image
      value: mouridamine/todo-app:latest
  workspaces:
    - name: source
      emptyDir: {} # Or use an emptyDir or other workspace options
