apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-git-repo
  namespace: tekton-app

spec:
  type: git
  params:
    - name: url
      value: https://github.com/amine620/tekton-app-test.git
    - name: revision
      value: master # or the branch you want to use
