apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-app
spec:
  params:
    - name: url
      type: string
      description: Repository URL to clone from.
    - name: revision
      type: string
      description: Repository branch or commit SHA to clone.
      default: "master"
    - name: subdirectory
      type: string
      description: Subdirectory inside the repo to initialize the workspace from.
      default: ""
    - name: deleteExisting
      type: string
      description: Clean out the contents of the repo's workspace before the clone.
      default: "true"
  workspaces:
    - name: output
      description: The destination directory where the repo will be cloned.
  steps:
    - name: clone
      image: alpine/git
      script: |
        if [ "$(params.deleteExisting)" == "true" ]; then
          rm -rf $(workspaces.output.path)/*
        fi
        git clone --branch $(params.revision) $(params.url) $(workspaces.output.path)/$(params.subdirectory)
