apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image
spec:
  type: image
  params:
    - name: url
      value: docker.io/<your-dockerhub-username>/<image-name>:latest
