apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: build
      taskRef:
        name: build-and-push
      resources:
        inputs:
          - name: source
            resource: git-source
        outputs:
          - name: docker-image
            resource: docker-image
