apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-run
spec:
  pipelineRef:
    name: build-and-push-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: app-git-repo
    - name: docker-image
      resourceRef:
        name: docker-image
